### ISSUE TITLE
Duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by wimbledon** [pubnative/pubnative-hybid-ios-sdk#320]
@can-soykarafakili, for the latest 2.4.0 SDK release, I get the following build error:
![image](https://user-images.githubusercontent.com/3291853/106986709-43d67d00-67af-11eb-9b49-f13c919a2635.png)
```
duplicate symbol '___PNLite_MRAID_mraid_js' in:
duplicate symbol '___PNLite_MRAID_mraid_js_len' in:
duplicate symbol '___PNLite_MRAID_CloseButton_png_len' in:
duplicate symbol '_pubnative_lite_vast_2_0_1_xsd_len' in:
duplicate symbol '___PNLite_MRAID_CloseButton_png' in:
duplicate symbol '_pubnative_lite_vast_2_0_1_xsd' in:
duplicate symbol '___PNLite_MRAID_mraid_js' in:
duplicate symbol '___PNLite_MRAID_mraid_js_len' in:
   ...
ld: 66 duplicate symbols for architecture x86_64
```

**Comment by can-soykarafakili** [comment]
Hey @wimbledon Can you provide more information about your current setup? For example:

- Did you use drag & drop method or cocoapods?
- I'm wondering somewhere in your project, do you have another copy of the HyBid.xcframework? 🤔
- Also some environmental information.

And also, did you apply "Removing the script" step, stated as a final note in this [step](https://github.com/pubnative/pubnative-hybid-ios-sdk/wiki/Setup-HyBid#install-hybid-sdk)

Before release, we've tried numerous tests with both integration methods and we have not encountered an error that you have... 🤔

**Comment by wimbledon** [comment]
I just did "pod update" from **Installing HyBid 2.4.0 (was 2.3.3)**
Xcode: 12.0.1 (12A7300)
iOS Deployment target: iOS 9.0+

**Comment by can-soykarafakili** [comment]
So I assume your issues are still continuing? If so, can you also try 

1) Deleting the `pod 'HyBid'  line from your podfile.
2) Running `pod install` command
3) Adding `pod 'HyBid', '2.4.0'` line to your podfile.
4) Runing `pod install --repo-update` command

**Comment by wimbledon** [comment]
@can-soykarafakili, 
Yes, the build error is still continuing after your suggested cocoapod steps.
I also `pod deintegrate` and removed the Pods directory and reinstall all pods, but the error remains.
The exact same error occurs when building for device (i.e. arm64) as well with 66 duplicate symbols.

**Comment by can-soykarafakili** [comment]
Super weird @wimbledon ,

Since I'm not experiencing the issue it is also hard for me to replicate and find a solution... 🤔 

I'm going to suggest few more things:
- Deleting the podfile.lock and doing a `pod install` again
- Checking if there is something fishy going on with your **Other Linker Flags** in your **Build Settings**

**Comment by wimbledon** [comment]
@can-soykarafakili, 
I resolved the issue by changing all Obj-C imports line from `@import HyBid;` to `#import <HyBid/HyBid.h>`.
Can you try to reproduce the build error by using `@import HyBid;`?

**Comment by can-soykarafakili** [comment]
@wimbledon In our GitHub Wiki, we've already stated that the import lines should be like this;

**Swift:**
```swift
import HyBid
```

**Objective-C:**
```objective-c
#import <HyBid/HyBid.h>
```

I have one Objective-C demo project that uses `#import <HyBid/HyBid.h>` and also one Swift project that uses `import HyBid` and both build without having any issues. So maybe you should have done it like this from the beginning? Because I'm thinking the otherway around wont even compile though... 🤔

**Comment by wimbledon** [comment]
@can-soykarafakili 
Yes, I've read the wiki.

I'm talking about Objective-C files specifically about this build error.
It's weird because the import worked perfectly in SDK 2.3.3 but duplicated symbols error in 2.4.0.

Please refer to https://stackoverflow.com/questions/18947516/import-vs-import-ios-7 for more context.
I believe the standard for Objective-C is to use `@import HyBid;` instead of old `#import <HyBid/HyBid.h>`.

Thoughts?

**Comment by can-soykarafakili** [comment]
Honestly, I have no idea right now @wimbledon ... 🤔 

To my project that has HyBid iOS SDK v:2.4.0 installed in Cocoapods, I've tried adding `@import HyBid;` to one of its Objective-C file. And it is not even compiling, saying `"Module 'HyBid' not found"`.

**Comment by wimbledon** [comment]
I see. Thank you for the effort and quick responses, @can-soykarafakili.
I'm able to build successfully now so I'm going to close this issue.

**Comment by can-soykarafakili** [comment]
No worries @wimbledon !! If we can find anything related with this I'll keep you updated 👍

**Comment by can-soykarafakili** [comment]
@wimbledon I've noticed that we changed the HyBid iOS SDK structure in HyBid.podspec file from v:2.3. to 2.4.0. (You can check for yourself as well) My guess is; the change that we've made could be the reason for the `@import HyBid;` is not working for you. Because when I've tried with 2.3.3, the `@import HyBid;` is working fine. So we have to look what caused this issue and if it is fixable, we'll fix it in an upcoming release.
